### ISSUE TITLE
TypeError: Preview is not a function

### ISSUE THREAD

**Issue by 001123** [johnsoncodehk/vite-plugin-vue-component-preview#1]
I have added Preview to vite.config.ts and main.ts but still got error when run dev.

Info:
OS WIN 11, node v16.16.0
vite": "^3.0.2"
"vite-plugin-vue-component-preview": "^0.2.1"

![image](https://user-images.githubusercontent.com/32441266/179885375-227671e1-82f5-48db-aaa1-54e79b03cdbe.png)
![image](https://user-images.githubusercontent.com/32441266/179885433-aff9f9d4-cedc-4ca4-ae1b-3d22569d9c6b.png)
![image](https://user-images.githubusercontent.com/32441266/179885412-171fe553-8a2d-4496-91e8-d2b7f864872b.png)

**Comment by Wxh16144** [comment]
try `Preview.default()`
