### ISSUE TITLE
ENOENT: no such file or directory, open '/src/HelloWorld.vue__preview.vue'

### ISSUE THREAD

**Issue by ByScripts** [johnsoncodehk/vite-plugin-vue-component-preview#10]
I installed the plugin then tried the example, but when I access `http://localhost:3000/__preview/src/HelloWorld.vue` I get the following error:

```
ENOENT: no such file or directory, open '/src/HelloWorld.vue__preview.vue'
```

**Comment by bennyty** [comment]
Also having this issue, and it has worked in the in my project.
