### ISSUE TITLE
Support mocking pinia/vuex stores, vue-router

### ISSUE THREAD

**Issue by segevfiner** [johnsoncodehk/vite-plugin-vue-component-preview#11]
To be able to preview less pure components that depends on pinia/vuex stores or vue-router, it would be useful to be able to specify mocks for them that would be used during preview.

**Comment by johnsoncodehk** [comment]
I think of two options:

1. Run your setup code in `<script setup>` block inside `<preview>`.

```html
<preview lang="md">

<script setup>
import { setupMock } from '@/store'
setupMock()
</script>

<slot />

</preview>
```

2. change the Vite running mode in VSCode settings. And judge it in your script to mock stores.

<img width="431" alt="螢幕截圖 2022-12-18 20 43 15" src="https://user-images.githubusercontent.com/16279759/208299013-67608fa2-d5ad-430a-88d4-125c73a69c18.png">

Are these enough to your use case?

**Comment by segevfiner** [comment]
The problem is that mocking stuff like stores mostly uses a Vue testing vue app from the vue test utils, I'm not sure how to set this up from inside a component.

**Comment by johnsoncodehk** [comment]
What about option 2.? You can use the following code in .ts / .js scripts. (If it's hard to set in .ts, I think it's even harder to set by this plugin.)
```ts
if (import.meta.env.MODE === 'preview') { 
    // mock...
}
```

**Comment by segevfiner** [comment]
Interesting, I guess there is no such env defined by default by Volar when starting the preview server. Still, now I have hit an issue with how to exactly mock pinia, it needs a `createSpy` function, I guess I can hook up sinon, but won't that leak memory?

Also it seems like it would be difficult setting the initial state of the store per component preview like this, and making sure that changes to it don't effect other preview component pages...

**Comment by johnsoncodehk** [comment]
> Interesting, I guess there is no such env defined by default by Volar when starting the preview server.

Yes, you need to config `volar.preview.script.vite` in VSCode settings for it.

> Still, now I have hit an issue with how to exactly mock pinia, it needs a `createSpy` function, I guess I can hook up sinon, but won't that leak memory?

I can't help because of lack of context...

> Also it seems like it would be difficult setting the initial state of the store per component preview like this, and making sure that changes to it don't effect other preview component pages...

When you change an active .vue document in VSCode, the component preview view will fully reload preview web page, so the component state will not be shared.

**Comment by segevfiner** [comment]
> > Still, now I have hit an issue with how to exactly mock pinia, it needs a `createSpy` function, I guess I can hook up sinon, but won't that leak memory?
> 
> I can't help because of lack of context...

Trying to stick a `@pinia/testing` instance instead of the normal pinia so actions default to being stubbed, and to somehow fill it with state suitable for preview.

```ts
if (import.meta.env.MODE === "preview") {
  app.use(createTestingPinia());
} else {
  app.use(createPinia());
}
```

**Comment by johnsoncodehk** [comment]
I actually haven't had a chance to try the `createSpy`, `createTestingPinia` API yet, so I'm not sure what block you're actually hitting.

@posva Can we have your advice?

**Comment by posva** [comment]
The testing pinia is an extended regular pinia instance that adds a plugin to stub actions and allow modifying getters. As long as one can call app.use(testingPinia) and setup the initial state (like in a test) on the testing pinia instance, one should be good.

to me, the check on mode seems to be enough but I haven’t tried it
