### ISSUE TITLE
question: reopen vue component preview tab

### ISSUE THREAD

**Issue by CheIIau** [johnsoncodehk/vite-plugin-vue-component-preview#13]
Maybe it's silly question but i just cant't figure it out. I closed the vue component preview tab and noticed there is no such item in explorer tab settings. I searched almost everywhere and didn't find a setting to add this tab again. maybe someone can help me with this?
![1](https://user-images.githubusercontent.com/58114735/206472868-ccfae29b-7f14-4434-a342-ebbd07df6846.jpg)
![2](https://user-images.githubusercontent.com/58114735/206472946-79856170-d4a4-4cae-9608-7ae12b6f153c.png)

**Comment by johnsoncodehk** [comment]
Try run `View: Reset View Locations` command in VSCode, and the component preview tab will back to initial location.
